# .coderabbit.yaml
language: "ko-KR" # 한국말로 설정
early_access: false
reviews:
  profile: "strict" 
  request_changes_workflow: true # 코드래빗이 리뷰 끝나면 알아서 PR 승인하게끔
  high_level_summary: true
  poem: true 
  review_status: false
  collapse_walkthrough: false
  auto_review:
    enabled: true
    drafts: false
chat:
  auto_reply: true