# .coderabbit.yaml

language: 'ko-KR'
early_access: false
reviews:
  profile: 'strict' 
  request_changes_workflow: false
  high_level_summary: true
  poem: true
  review_status: true
  collapse_walkthrough: false
  auto_review:
    enabled: true
    drafts: false
    base_branches: ".*"
chat:
  auto_reply: true