export { default as IconFail } from './fail.svg'
export { default as Logo } from './logo.svg'
export { default as IconSuccess } from './success.svg'
export { default as IconVisibilityOff } from './visibility-off.svg'
export { default as IconVisibilityOn } from './visibility-on.svg'
