import Navbar from '@/components/layout/Navbar'
import '@/styles/globals.css'
import type { Metadata } from 'next'
import Script from 'next/script'
import { Providers } from './providers'

export const metadata: Metadata = {
    title: '축의금 분석하기',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <head>
                <Script src="https://www.googletagmanager.com/gtag/js?id=G-2N63BVZPXP" strategy="afterInteractive" />
                <Script id="ga-init" strategy="afterInteractive">
                    {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-2N63BVZPXP');
          `}
                </Script>
            </head>
            <body>
                <div id="portal"></div>
                <Providers>
                    <Navbar />
                    <main className="pt-[120px] pb-[100px]">{children}</main>
                </Providers>
            </body>
        </html>
    )
}
