import KakaoScript from '@/features/analyze-result/model/kakao-script'
import GnbLayout from '@/features/gnb/components/gnb-layout'
import '@/styles/globals.css'
import type { Metadata } from 'next'
import { Providers } from './providers'

export const metadata: Metadata = {
    title: '축의금 분석하기',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body>
                <div id="portal"></div>
                <Providers>
                    <GnbLayout />
                    <main className="pt-[120px] pb-[100px]">{children}</main>
                </Providers>
                <KakaoScript />
            </body>
        </html>
    )
}
